name: Documentation

on:
  workflow_dispatch:
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  documentation:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Doxygen Generation
      uses: mattnotmitt/doxygen-action@1.9.5
      with:
        doxyfile-path: ./DoxygenConfig
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updating documentation